version: '3'

services:
  db:
    image: postgres:13.5
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=root
      - POSTGRES_DB=app
    volumes:
      - ./psql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
